CODE/PCBuilder3/PCBuilder3/Controllers/BuildController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PCBuilder3.Models;

namespace PCBuilder3.Controllers
{
    public class BuildController : Controller
    {
        // GET: Build
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Build(double budget, int type)
        {
            DataClasses1DataContext db = new DataClasses1DataContext();
            double cpu = 0;
            double main = 0;
            double ram;
            double hdd = 0;
            double ssd = 0;
            double psu = 0;
            double vga = 0;
            List<string> lres = new List<string>();
            //Office
            if (type == 1)
            {
                //CPU
                cpu = (double)(30 * budget / 100);

                var cpures = (from search in db.CPUs
                              where (search.Gia <= cpu && (search.Loai == 1 || search.Loai == 2)) 
                              orderby search.Gia descending
                              select search).Take(1);
                List<CPU> cpusearchres = new List<CPU>();
                foreach (CPU res in cpures)
                {
                    cpusearchres.Add(res);
                }

                //MAIN
                if (budget <= 5000000) main = 1600000;
                else if (budget <= 8000000) main = 2000000;
                else if (budget <= 10000000) main = 2500000;
                else if (budget <= 15000000) main = 2800000;
                else if (budget <= 20000000) main = 3300000;
                else main = 4000000;
                var mainres = (from search in db.MainBoards
                               where (search.Gia <= main && search.Loai >= cpusearchres[0].Loai && search.Socket == cpusearchres[0].Socket)
                               orderby search.Gia descending
                               select search).Take(1);
                List<MainBoard> mainsearchres = new List<MainBoard>();
                foreach (MainBoard res in mainres)
                {
                    mainsearchres.Add(res);
                }

                //HDD
                if (budget <= 7000000) hdd = 1100000;
                else if (budget <= 10000000) hdd = 1200000;
                else if (budget <= 20000000) hdd = 2000000;
                else hdd = 4000000;
                var hddres = (from search in db.OCungs
                              where (search.Gia <= hdd && search.Loai == "HDD")
                              orderby search.Gia descending
                              select search).Take(1);
                List<OCung> hddsearchres = new List<OCung>();
                foreach (OCung res in hddres)
                {
                    hddsearchres.Add(res);
                }

                //SSD
                if (budget <= 7000000) ssd = 0;
                else if (budget <= 15000000) ssd = 128;
                else if (budget <= 30000000) ssd = 256;
                else if (budget <= 40000000) ssd = 512;
                else ssd = 1024;
                var ssdprice = 0;
                if (budget <= 7000000) ssdprice = 0;
                else if (budget <= 15000000) ssdprice = 1300000;
                else if (budget <= 20000000) ssdprice = 2000000;
                else if (budget <= 30000000) ssdprice = 3000000;
                else if (budget <= 35000000) ssdprice = 5000000;
                else if (budget <= 40000000) ssdprice = 8000000;
                else ssdprice = 10000000;
                var ssdres = (from search in db.OCungs
                              where (search.DungLuong <= ssd && search.Gia <= ssdprice && search.Loai == "SSD")
                              orderby search.Gia descending
                              select search).Take(1);
                List<OCung> ssdsearchres = new List<OCung>();
                foreach (OCung res in ssdres)
                {
                    ssdsearchres.Add(res);
                }

                //PSU
                if (budget <= 7000000) psu = 500000;
                else if (budget <= 10000000) psu = 700000;
                else if (budget <= 15000000) psu = 900000;
                else if (budget <= 20000000) psu = 1000000;
                else if (budget <= 30000000) psu = 2000000;
                else psu = 10000000;
                var psures = (from search in db.PSUs
                              where (search.Gia <= psu)
                              orderby search.Gia descending
                              select search).Take(1);
                List<PSU> psusearchres = new List<PSU>();
                foreach (PSU res in psures)
                {
                    psusearchres.Add(res);
                }


                //    if (budget <= 10000000) ram = "4GB";
                //    else if (budget <= 15000000) ram = "8GB";
                //    else ram = "16GB";
                lres.Add(mainsearchres[0].ID.ToString());
                lres.Add(mainsearchres[0].Ten.ToString());
                lres.Add(mainsearchres[0].Gia.ToString());
                lres.Add(cpusearchres[0].ID.ToString());
                lres.Add(cpusearchres[0].Ten.ToString());
                lres.Add(cpusearchres[0].Gia.ToString());
                lres.Add(hddsearchres[0].ID.ToString());
                lres.Add(hddsearchres[0].Ten.ToString());
                lres.Add(hddsearchres[0].Gia.ToString());
                lres.Add(psusearchres[0].ID.ToString());
                lres.Add(psusearchres[0].Ten.ToString());
                lres.Add(psusearchres[0].Gia.ToString());
                if (ssdsearchres.Count != 0)
                {
                    lres.Add(ssdsearchres[0].ID.ToString());
                    lres.Add(ssdsearchres[0].Ten.ToString());
                    lres.Add(ssdsearchres[0].Gia.ToString());
                }
                else
                {
                    lres.Add("No SSD");
                    lres.Add("No SSD");
                    lres.Add("No SSD");
                }
                return Json(lres, JsonRequestBehavior.AllowGet);

            }
            //Gaming
            if (type == 2)
            {
                //CPU
                cpu = (double)(27 * budget / 100);
                var cpures = (from search in db.CPUs
                              where (search.Gia <= cpu && search.Loai != 4 && search.ThuongHieu != "AMD")
                              orderby search.Loai descending, search.Gia descending
                              select search).Take(1);
                List<CPU> cpusearchres = new List<CPU>();
                foreach (CPU res in cpures)
                {
                    cpusearchres.Add(res);
                }

                //VGA
                if (budget <= 7000000) vga = 1700000;
                else if (budget <= 8000000) vga = 2500000;
                else if (budget <= 10000000) vga = 3000000;
                else if (budget <= 15000000) vga = 4000000;
                else if (budget <= 20000000) vga = 7000000;
                else if (budget <= 25000000) vga = 12000000;
                else if (budget <= 30000000) vga = 17000000;
                else if (budget <= 40000000) vga = 18000000;
                else if (budget <= 50000000) vga = 20000000;
                else if (budget <= 60000000) vga = 25000000;
                else vga = 1000000000;
                var vgares = (from search in db.VGAs
                              where (search.Gia <= vga && search.ThuongHieu != "Nvidia")
                              orderby search.Gia descending
                              select search).Take(1);
                List<VGA> vgasearchres = new List<VGA>();
                foreach (VGA res in vgares)
                {
                    vgasearchres.Add(res);
                }

                //MAIN
                if (budget <= 5000000) main = 1600000;
                else if (budget <= 8000000) main = 2000000;
                else if (budget <= 10000000) main = 2500000;
                else if (budget <= 15000000) main = 2800000;
                else if (budget <= 20000000) main = 3300000;
                else main = 4000000;
                var mainres = (from search in db.MainBoards
                               where (search.Gia <= main && search.Loai == cpusearchres[0].Loai)
                               orderby search.Gia descending
                               select search).Take(1);
                List<MainBoard> mainsearchres = new List<MainBoard>();
                foreach (MainBoard res in mainres)
                {
                    mainsearchres.Add(res);
                }

                //HDD
                if (budget <= 7000000) hdd = 1100000;
                else if (budget <= 10000000) hdd = 1200000;
                else if (budget <= 20000000) hdd = 2000000;
                else hdd = 3000000;
                var hddres = (from search in db.OCungs
                              where (search.Gia <= hdd && search.Loai == "HDD")
                              orderby search.Gia descending
                              select search).Take(1);
                List<OCung> hddsearchres = new List<OCung>();
                foreach (OCung res in hddres)
                {
                    hddsearchres.Add(res);
                }

                //SSD
                if (budget <= 7000000) ssd = 0;
                else if (budget <= 15000000) ssd = 128;
                else if (budget <= 30000000) ssd = 256;
                else if (budget <= 40000000) ssd = 512;
                else ssd = 1024;
                var ssdprice = 0;
                if (budget <= 7000000) ssdprice = 0;
                else if (budget <= 15000000) ssdprice = 1300000;
                else if (budget <= 20000000) ssdprice = 1800000;
                else if (budget <= 30000000) ssdprice = 2000000;

CODE/PCBuilder3/PCBuilder3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PC Builder</title>
    @*@Styles.Render("~/Content/css")
    @Styles.Render("~/CSS/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts")*@
    @*<link href="css/StyleSheet.css" rel="stylesheet" type="text/css" />*@
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <link rel="stylesheet" href="~/Content/Site.css" />
    <link rel="stylesheet" href="~/CSS/Layout.css" />
    @*<link rel="stylesheet" href="CSS/font-awesome-4.6.3/css/font-awesome.min.css" type="text/css" />*@
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />

    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/build.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.js" type="text/javascript"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" id="top-nav-bar" >
        <div class="container" >
            <div class="navbar-header" >
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("PC Builder", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                <li>
                    <a href="@Url.Action("Index", "Home")" title="Home" class="links">
                        <img alt="Home" src="@Url.Content("~/Image/logo.png")" style="height: 40px; width: 150px; margin-top: 5px;">                        
                    </a>
                </li>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Shopping", "Index", "Store")</li>
                    <li>@Html.ActionLink("PC Build", "Index", "Build")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @*<li>
                        <form>
                            <div class="input-group" id="search-bar">
                                <input type="text" class="form-control" placeholder="Search">
                                @*<div class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <i class="glyphicon glyphicon-search"></i>
                                    </button>
                                </div
                            </div>
                        </form>
                    </li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr/>
        <div class="footer">
            <div class="wrap">
                <div class="section group">
                    <div class="col_1_of_4 span_1_of_4">
                        <h4>Information</h4>
                        <ul>
                            <li><a href="about.html">About Us</a></li>
                            <li><a href="contact.html">Customer Service</a></li>
                            <li><a href="delivery.html">Orders and Returns</a></li>
                            <li><a href="contact.html">Contact Us</a></li>
                        </ul>
                    </div>
                    <div class="col_1_of_4 span_1_of_4">
                        <h4>Why us</h4>
                        <ul>
                            <li><a href="about.html">About Us</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>
                    </div>
                    <div class="col_1_of_4 span_1_of_4">
                        <h4>My account</h4>
                        <ul>
                            <li><a href="contact.html">Sign In</a></li>
                            <li><a href="index.html">View Cart</a></li>
                            <li><a href="#">My Wishlist</a></li>
                            <li><a href="contact.html">Help</a></li>
                        </ul>
                    </div>
                    <div class="col_1_of_4 span_1_of_4">
                        <h4>Contact</h4>
                        <ul>
                            <li><span>(+84) 0915866373</span></li>
                        </ul>
                        <div class="social-icons">
                            <h4>Follow Us</h4>
                            <ul>
                                <li><a href="#" target="_blank"><i class="fa fa-facebook-official" aria-hidden="true"></i></a></li>
                                <li><a href="#" target="_blank"><i class="fa fa-twitter-square" aria-hidden="true"></i></a></li>
                                <div class="clear"></div>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>